server:
  port: 8092
spring:
  application:
    name: seller-service
  zipkin:
    base-url: http://127.0.0.1:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  profiles:
    active: mysql

  jpa:
    hibernate:
      ddl-auto: create
    #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
#    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka

logging:
  level:
    shop.kokodo.sellerservice.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, prometheus, metrics

product-service:
  url: http://PRODUCT-SERVICE/product-service/product
  exception:
    product_is_empty: There is no item

---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:./test
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/calculate
      username: sa
      password:
      driver-class-name: org.h2.Driver
---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/mydb
      username: root
      password:
      driver-class-name: com.mysql.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always